### ISSUE TITLE
About the method

### ISSUE THREAD

**Issue by mingliangzhang2018** [YyzHarry/imbalanced-semi-self#1]
Thank you for sharing your interesting work. Would you mind clarify that what is the method of "CE(Balanced)" ?

**Comment by YyzHarry** [comment]
Hi, thanks for your interest! "CE(Balanced)" means CE with class-balanced sampling.

**Comment by mingliangzhang2018** [comment]
> Hi, thanks for your interest! "CE(Balanced)" means CE with class-balanced sampling.

Thanks!

**Comment by mingliangzhang2018** [comment]
I still have some questions. At first, why not apply models of ResNeXt same as  the paper "DECOUPLING"? Secondly, I find that you use small batch size (100 or 128) in the models training with SSP for the datasets of Imagenet-LT and iNat2018. Do you test the performance of all baseline methods without SSP using same batch size?  In other words, whether or not the performance improvement mainly comes from the adjustment of the batch size but less from SSP?

**Comment by YyzHarry** [comment]
- ResNeXt architecture: Simply because we have limited computation resources. As we are comparing to many methods rather than only decoupling method, we just choose 1-2 representative architectures. I believe similar results should hold for different architectures.
- Batch size: For ImageNet-LT I'm using 128 for all models (and 100 for iNat), as these are the maximum size my GPU can hold. Note that both the baselines and models with SSP are using the __same__ training setups, despite the latter one loading a pre-trained model.

**Comment by mingliangzhang2018** [comment]
> * ResNeXt architecture: Simply because we have limited computation resources. As we are comparing to many methods rather than only decoupling method, we just choose 1-2 representative architectures. I believe similar results should hold for different architectures.
> * Batch size: For ImageNet-LT I'm using 128 for all models (and 100 for iNat), as these are the maximum size my GPU can hold. Note that both the baselines and models with SSP are using the **same** training setups, despite the latter one loading a pre-trained model.

thank you very much!
