### ISSUE TITLE
How to apply to traditional ML techniques such as lightgbm?

### ISSUE THREAD

**Issue by tangwudu** [YyzHarry/imbalanced-semi-self#12]
As indicated by the question, is it possible to apply your method to traditional machine learning techniques and how?

**Comment by YyzHarry** [comment]
Hi - thank you for your interest! Sorry for the late reply as there were some major deadlines around.

For your question, the overall answer should be mostly yes --- since the two methods should be independent of the learning technique itself. However, I believe there are also some case-by-case restrictions:
- __Semi-supervised__: If you have additional unlabeled data (and assume they are relevant enough), you should be able to use any technique. You can apply the self-training routine as, first use labeled data to train a model, then do pseudo-labeling for unlabeled data based on the intermediate model, then combine all data to train a final model.
- __Self-supervised__: In self-supervised case it becomes more complicated. Typically we assume a (sub)set of the model parameters can be trained via a designed self-supervised task in the first stage, which gives you good initialization when the imbalanced labels are used in the normal training stage. Here it seems to have restrictions on the learning technique you select.

Hope this helps!
