### ISSUE TITLE
Have you ever tried "Semi-Supervised Imbalanced Learning on ImageNet-LT"?

### ISSUE THREAD

**Issue by e96031413** [YyzHarry/imbalanced-semi-self#18]
Hi, have you ever tried "Semi-Supervised Imbalanced Learning" on ImageNet-LT?

According to the experiment result in the paper, the performance with Semi-Supervised Imbalanced Learning seems better than Self-Supervised Imbalanced Learning on CIFAR-10-LT.

If I want to try this experiment, how can I modify the [dataset/imagenet.py](https://github.com/YyzHarry/imbalanced-semi-self/blob/master/dataset/imagenet.py) to dataset/imblance_imagenet.py (similar to imblance_cifar.py)?

**Comment by YyzHarry** [comment]
Hi, we did not try semi-supervised imbalanced learning on ImageNet-LT. The main reason is that we do not have a larger extra unlabeled dataset for it. FYI, CIFAR-10 has the TinyImages as the extra unlabeled dataset, as we descirbed in the paper.

I guess one way to include more unlabeled data could be using the unused data in the original ImageNet (since ImageNet-LT uses only a subset of ImageNet).

**Comment by e96031413** [comment]
OK, Thanks for your reply
