### ISSUE TITLE
moco on cifar dataset

### ISSUE THREAD

**Issue by IssacCyj** [YyzHarry/imbalanced-semi-self#19]
Thanks for the great repo!

I have a quick question, is there any specific reason not adding cifar&svhn datasets to the moco training script? like, it's not suitable or the performance is really bad on the small datasets?

Thanks!

**Comment by YyzHarry** [comment]
Hi, thanks for your interest!

We provided experiment results of MoCo on CIFAR in Appendix Table 9 of our [paper](https://arxiv.org/pdf/2006.07529.pdf). It could bring improvements over the baseline, but is not as much as using Rotation. My guess is that since MoCo needs a large number of (negative) samples to be effective, the smaller yet imbalanced datasets thus may not benefit much from MoCo, compared to those with larger size and more samples (such as ImageNet).
